version: "3.9"

services:
  app:
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    build: ./docker/php
    volumes:
      - .:/var/www/html
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
  server:
    container_name: "${COMPOSE_PROJECT_NAME}-server"
    image: nginx:alpine
    depends_on:
      - app
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
